Update dependencies
balena-io-modules/abstract-sql-to-typescript pull request #51
Opened 2024-02-29 15:45 UTC by Page-

Update @balena/abstract-sql-compiler from 9.0.3 to 9.0.4 Update @balena/odata-to-abstract-sql from 5.9.6 to 6.2.3

Change-type: patch

2024-02-29 16:10 UTC, otaviojacobi requested changes
@Page- I think you have lint & lint-fix reversed

2024-02-29 16:10 UTC, otaviojacobi commented on package.json
> +    "lint": "balena-lint --fix src test && tsc --noEmit"
Here lint-fix should have --fix & lint should just do the check

2024-02-29 17:14 UTC, otaviojacobi commented
@Page-  I think you migh have forgotten to push

2024-03-04 11:23 UTC, Page- commented
Apparently so, fixed @otaviojacobi

2024-03-04 11:26 UTC, otaviojacobi approved these changes

2024-03-04 11:26 UTC, merged